aws_region            = "us-east-1"
profile               = "default"
api_name              = "bouncer"
api_basepath          = "bouncer"
api_stage_name        = "test"
lambda_function_name  = "RegisterApp_Lambda"
lambda_authorizer_uri = "arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:426831243303:function:RegisterApp_Lambda/invocations"
lambda_function_uri   = "arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:426831243303:function:RegisterApp_Lambda/invocations"